//! The dioxus-decompositions web app: drop a CSV, TSV or Parquet file, reduce
//! with PCA, embed with a selectable decomposition and watch the scatter plot
//! animate as epochs progress. Also serves as the reference consumer of the
//! dioxus-decompositions component library.

use dioxus::prelude::*;
use dioxus_decompositions::{DecompositionExplorer, ExampleDataset};

/// URL of the worker loader module, generated by build.rs into public/worker/
/// together with the wasm bundle it initializes. dx serves public/ at the
/// site root.
const WORKER_LOADER_URL: &str = "/worker/loader.js";

/// MNIST subsample (1000 digits, PCA-50, snappy Parquet) offered as a one
/// click example dataset.
static MNIST_EXAMPLE: Asset = asset!("/assets/examples/mnist_1k.parquet");

/// Cora citation dataset (2708 papers, 1433 binary bag of words features,
/// 7 subjects), shipped raw so the in-worker PCA preprocessing does the
/// reduction to 50 dimensions.
static CORA_EXAMPLE: Asset = asset!("/assets/examples/cora.parquet");

/// Minimal page shell styling, the component brings its own default theme.
const APP_STYLE: &str = "
body {
    margin: 0;
    padding: 2rem 1.5rem;
    display: flex;
    justify-content: center;
    background: #ffffff;
    font-family: system-ui, -apple-system, 'Segoe UI', sans-serif;
}
main { width: 100%; max-width: 56rem; }
h1 { font-size: 1.35rem; font-weight: 600; color: #1c2733; margin: 0 0 1rem; }
@media (prefers-color-scheme: dark) {
    body { background: #14181d; }
    h1 { color: #e7ecf1; }
}
";

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    rsx! {
        style { {APP_STYLE} }
        main {
        h1 { "dioxus-decompositions" }
        DecompositionExplorer {
            worker_url: WORKER_LOADER_URL,
            examples: vec![
                ExampleDataset {
                    name: String::from("MNIST digits (1k, PCA-50)"),
                    url: MNIST_EXAMPLE.to_string(),
                },
                ExampleDataset {
                    name: String::from("Cora papers (2.7k, 1433 raw features)"),
                    url: CORA_EXAMPLE.to_string(),
                },
            ],
        }
        }
    }
}
